name: CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build

      - name: Create Pull Request
        if: success() && github.ref == 'refs/heads/dev'
        uses: actions/github-script@v6
        with:
          script: |
            try {
              // 기존 PR이 있는지 확인
              const existingPRs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                head: `${context.repo.owner}:dev`,
                base: 'main'
              });
              
              // 기존 PR이 없을 경우에만 새 PR 생성
              if (existingPRs.data.length === 0) {
                await github.rest.pulls.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  head: 'dev',
                  base: 'main',
                  title: 'Create Pull Request from dev to main',
                  body: 'Automatically creating a pull request from dev to main after a successful build',
                });
                console.log("Pull request created successfully");
              } else {
                console.log("Pull request already exists, skipping creation");
              }
            } catch (error) {
              console.error("Error handling pull request:", error);
            }
